-- 150_anthony_p5c_print_runs_tearsheets.sql
-- Anthony Phase 5c — store the per-page tearsheet manifest on the
-- print_runs row. Each entry is { page, pdf_url, bunny_path, byte_size }.
-- Generated by the generate-tearsheets edge function which splits the
-- master PDF using pdf-lib and uploads each page back to BunnyCDN.
ALTER TABLE print_runs
  ADD COLUMN IF NOT EXISTS tearsheets jsonb;

CREATE INDEX IF NOT EXISTS idx_print_runs_with_tearsheets
  ON print_runs(issue_id) WHERE tearsheets IS NOT NULL;
